---
- name: setup
  hosts: all
  user: root
  vars:
    password: zaheshovany heslo

  tasks:
    - name: set password
      user: name=tset password={{password}}

    - name: Install vim
      action: command: sudo apt-get install vim
