---
- name: SSH
  hosts: all
  tags: ssh

  tasks:
    - name: Ensure root ssh directory exists
      file:
        path: /root/.ssh
        state: directory

    - name: Import SSH keys
      authorized_key:
        user: root
        key: '{{ item }}'
        state: present
      loop: '{{ ssh_keys }}'
      
- name: Users
  hosts: all
  tags: users

  vars:
    username: user
    shell: /bin/bash 
    
    tasks:
    
    - name: user
      user:
        name: "{{ username }}"
        shell: "{{ shell }}"
        state: present

- name: Install Vim
  hosts: all

  tasks:
    - name: Install Vim
      package:
        name: vim
        state: present
